In [1]:
import numpy as np
import pandas as pd

### 练习一

In [2]:
thrones = pd.read_csv('../data/Game_of_Thrones_Script.csv')

In [3]:
thrones

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2011/4/17,Season 1,Episode 1,Winter is Coming,waymar royce,What do you expect? They're savages. One lot s...
1,2011/4/17,Season 1,Episode 1,Winter is Coming,will,I've never seen wildlings do a thing like this...
2,2011/4/17,Season 1,Episode 1,Winter is Coming,waymar royce,How close did you get?
3,2011/4/17,Season 1,Episode 1,Winter is Coming,will,Close as any man would.
4,2011/4/17,Season 1,Episode 1,Winter is Coming,gared,We should head back to the wall.
...,...,...,...,...,...,...
23906,2019/5/19,Season 8,Episode 6,The Iron Throne,brienne,I think we can all agree that ships take prece...
23907,2019/5/19,Season 8,Episode 6,The Iron Throne,bronn,I think that's a very presumptuous statement.
23908,2019/5/19,Season 8,Episode 6,The Iron Throne,tyrion lannister,I once brought a jackass and a honeycomb into ...
23909,2019/5/19,Season 8,Episode 6,The Iron Throne,man,The Queen in the North!
23910,2019/5/19,Season 8,Episode 6,The Iron Throne,all,The Queen in the North! The Queen in the North...

In [4]:
thrones.Name.nunique()

564

In [6]:
thrones.Name.value_counts().head(1)

tyrion lannister    1760
Name: Name, dtype: int64

In [20]:
thrones['length'] = thrones.Sentence.apply(lambda x:len(x.split(' ')))

In [53]:
thrones.groupby('Name').length.sum().sort_values(ascending=False).head(1)

Name
tyrion lannister    26009
Name: length, dtype: int64

### 练习二

In [26]:
kobe = pd.read_csv('../data/Kobe_data.csv', index_col = 'shot_id')

In [27]:
kobe

,action_type,combined_shot_type,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,...,shot_made_flag,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,team_id,team_name,game_date,matchup,opponent
shot_id,,,,,,,,,,,,,,,,,,,,,
1,Jump Shot,Jump Shot,10,20000012,33.9723,167,72,-118.1028,10,1,...,NaN,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000/10/31,LAL @ POR,POR
2,Jump Shot,Jump Shot,12,20000012,34.0443,-157,0,-118.4268,10,1,...,0.0,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,1610612747,Los Angeles Lakers,2000/10/31,LAL @ POR,POR
3,Jump Shot,Jump Shot,35,20000012,33.9093,-101,135,-118.3708,7,1,...,1.0,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000/10/31,LAL @ POR,POR
4,Jump Shot,Jump Shot,43,20000012,33.8693,138,175,-118.1318,6,1,...,0.0,2PT Field Goal,Right Side Center(RC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000/10/31,LAL @ POR,POR
5,Driving Dunk Shot,Dunk,155,20000012,34.0443,0,0,-118.2698,6,2,...,1.0,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000/10/31,LAL @ POR,POR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30693,Jump Shot,Jump Shot,397,49900088,33.9963,1,48,-118.2688,6,4,...,0.0,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000/6/19,LAL vs. IND,IND
30694,Tip Shot,Tip Shot,398,49900088,34.0443,0,0,-118.2698,6,4,...,NaN,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000/6/19,LAL vs. IND,IND
30695,Running Jump Shot,Jump Shot,426,49900088,33.8783,-134,166,-118.4038,3,4,...,1.0,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000/6/19,LAL vs. IND,IND
30696,Jump Shot,Jump Shot,448,49900088,33.7773,31,267,-118.2388,2,4,...,0.0,3PT Field Goal,Center(C),Above the Break 3,24+ ft.,1610612747,Los Angeles Lakers,2000/6/19,LAL vs. IND,IND
30697,Jump Shot,Jump Shot,471,49900088,33.9723,1,72,-118.2688,0,4,...,0.0,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000/6/19,LAL vs. IND,IND

In [59]:
# kobe.groupby(['action_type', 'combined_shot_type']).game_event_id.nunique().sort_values(ascending=False).head()

In [58]:
pd.Series(list(zip(kobe['action_type'], kobe['combined_shot_type']))).value_counts().head()

(Jump Shot, Jump Shot)               18880
(Layup Shot, Layup)                   2567
(Driving Layup Shot, Layup)           1978
(Turnaround Jump Shot, Jump Shot)     1057
(Fadeaway Jump Shot, Jump Shot)       1048
dtype: int64

In [47]:
# kobe.opponent.value_counts().sort_values(ascending=False).head()

In [46]:
kobe.groupby('opponent').game_id.nunique().sort_values(ascending=False).head()

opponent
SAS    91
PHX    87
UTA    84
DEN    83
POR    81
Name: game_id, dtype: int64

In [75]:
pd.Series(list(zip(*(pd.Series(list(zip(kobe['game_id'], kobe['opponent']))).unique()).tolist()))[1]).value_counts().head()

SAS    91
PHX    87
UTA    84
DEN    83
POR    81
dtype: int64